version: 0.2
# GET REPOSITORY NAME: serve-image-h4dhsvp16m4n
phases:
  build:
    commands:
      - docker build -f infrastructure/Dockerfile -t serverless-app .
  post_build:
    commands:
      - eval $(aws ecr get-login --region eu-west-1 --registry-ids 193006638607) && docker tag serverless-app:latest 193006638607.dkr.ecr.eu-west-1.amazonaws.com/serve-image-h4dhsvp16m4n:latest && docker push 193006638607.dkr.ecr.eu-west-1.amazonaws.com/serve-image-h4dhsvp16m4n:latest

### eval $(aws ecr get-login --registry-ids 193006638607) && 

