version: 0.2
# GET REPOSITORY NAME: serve-image-h4dhsvp16m4n ?
# ENV VARS
#ECR_ACCOUNT_ID
#ECR_IMAGE_TAG
phases:
  build:
    commands:
      - docker build -f infrastructure/Dockerfile -t ${ECR_IMAGE_TAG} .
  post_build:
    commands:
      - eval $(aws ecr get-login --region eu-west-1 --registry-ids ${ECR_ACCOUNT_ID}) && docker push ${ECR_IMAGE_TAG}

