version: 0.2
phases:
  build:
    commands:
      - docker build -f infrastructure/Dockerfile -t serverless-app .
  post_build:
    commands:
      - eval $(aws ecr get-login --registry-ids 193006638607) && docker push serverless-app

# next returns an error ... AUTHENTICATION
# aws ecr get-login --no-include-email --region eu-west-1
# docker tag maven_image:latest 193006638607.dkr.ecr.eu-west-1.amazonaws.com/serve-image-serve-image-XXXX:serverless-app
# docker push 193006638607.dkr.ecr.eu-west-1.amazonaws.com/serve-image-serve-image-XXXX:serverless-app
