
version: 0.2

phases:
  build:
    commands:
      - docker build -f infrastructure/Dockerfile -t maven_image:1.0 .
  post_build:
    commands:
      - ECR_ACCOUNT_ID=193006638607
      - eval $(aws ecr get-login --registry-ids ${ECR_ACCOUNT_ID}) && docker push maven_image:1.0 
